// console.log(document.title)
// document.title = 'changed'

// console.log(typeof document.body)

// console.log(document.body.innerHTML)
// document.body.innerHTML = '<button>good job </button>'
/*
document.body.innerHTML = "hello";
document.title = 'Good job!';

*/

console.log(document.querySelector('button').innerHTM)
document.querySelector('button').innerHTML = 'Changed';

const buttonEl = document.querySelector('.js-button')

console.log(buttonEl);